Inventory interaction review
Dystopian/ACE3 pull request #2
Opened 2023-07-07 04:08 UTC by LinkIsGrim

Code style changes and a few condition improvements.

2023-07-07 22:05 UTC, Dystopian requested changes

2023-07-07 22:05 UTC, Dystopian commented on addons/interaction/CfgVehicles.hpp
> +                    condition = QUOTE(!((lifeState _target) in [ARR_2('HEALTHY','INJURED')]));
```suggestion
                    condition = QUOTE(!(lifeState _target in [ARR_2('HEALTHY','INJURED')]));
```
Also why remove in-vehicle check?

2023-07-07 22:05 UTC, Dystopian commented on addons/dragging/functions/fnc_canCarry.sqf
> +    (lifeState _target) isEqualTo "INCAPACITATED"
```suggestion
    lifeState _target isEqualTo "INCAPACITATED"
```
Are you sure this is the same as `animationState _target in ["", "unconscious"]` and `{_target getVariable ["ACE_isUnconscious", false]}`? I'm not good in vanilla revive and ACE Medical so can't argue.
Here and below

2023-07-07 22:05 UTC, Dystopian commented on addons/interaction/XEH_postInit.sqf
> +    {count (weaponCargo _target) isEqualTo 1},
```suggestion
    {count weaponCargo _target == 1},
```
no reason for `isEquaTo`

2023-07-07 22:17 UTC, rautamiekka commented on addons/interaction/XEH_postInit.sqf
> +    {count (weaponCargo _target) isEqualTo 1},
Surely `isEqualTo` won't make it worse, at least ?

2023-07-08 00:42 UTC, Dystopian commented on addons/interaction/XEH_postInit.sqf
> +    {count (weaponCargo _target) isEqualTo 1},
at least it's much less readable then `==` so we should use it when we really need performance (and have it actually)

2023-07-08 06:19 UTC, LinkIsGrim commented on addons/dragging/functions/fnc_canCarry.sqf
> +    (lifeState _target) isEqualTo "INCAPACITATED"
Yes.

2023-07-08 06:21 UTC, LinkIsGrim commented on addons/interaction/CfgVehicles.hpp
> +                    condition = QUOTE(!((lifeState _target) in [ARR_2('HEALTHY','INJURED')]));
I'm stupid and forgot to readd during testing.

See below for brackets.

2023-07-08 06:21 UTC, LinkIsGrim commented on addons/interaction/XEH_postInit.sqf
> +    {count (weaponCargo _target) isEqualTo 1},
/shrug

Still prefer the brackets, though.

2023-07-09 09:45 UTC, Dystopian commented on addons/dragging/functions/fnc_canCarry.sqf
> +    (lifeState _target) isEqualTo "INCAPACITATED"
> I'm not an expert on operand order in SQF

See https://foxhound.international/precedence-arma-3-sqf.html. It should be on biki but looks like nobody cares.

2023-07-09 09:47 UTC, Dystopian requested changes
Recent upstream merge broke PR and now many other files are changed :(
I don't really know how to fix it and am not sure if I should merge the PR,

2023-07-09 13:39 UTC, LinkIsGrim commented
Merge upstream in Dystopian/inventory-interaction and it'll sort itself out.

2023-07-09 20:00 UTC, merged